name: Infrastructure Destroy
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  Destroy-Infrastructure:
    name: 'Terraform to destroy Infra'
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_appId: ${{ secrets.ARM_CLIENT_ID }}
      TF_VAR_password: ${{ secrets.ARM_CLIENT_SECRET }}
      TF_VAR_github_token: ${{ secrets.GIT_TOKEN }}
      TF_VERSION: 1.7.5
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: Terraform init
        id: init
        run: terraform init
      - name: Terraform destroy
        id: apply
        run: terraform destroy -auto-approve
  Delete-PreRequisite:
    needs: Destroy-Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: 'Login on Azure'
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Run Azure Pre-Requisites CLI commands'
        run: |
            az group delete --name sas-test-tf
